services:
  db:
    platform: linux/arm64
    image: postgres:15
    container_name: local-postgres
    restart: unless-stopped
    # Remove external port exposure, only accessible within Docker network
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-hagenhub}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-postgres}", "-d", "${DB_NAME:-hagenhub}"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 5s

  pgbouncer:
    image: bitnami/pgbouncer:1.18.0
    ports:
      - "5432:6432"
    environment:
      - POSTGRESQL_USERNAME=${DB_USER:-postgres}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRESQL_HOST=db
      - POSTGRESQL_DATABASE=${DB_NAME:-hagenhub}
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_MAX_CLIENT_CONNECTIONS=100
      - PGBOUNCER_DEFAULT_POOL_SIZE=20
      - PGBOUNCER_PORT=6432
    depends_on:
      - db

volumes:
  pgdata: