name: Database Deploy

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      db_flag:
        description: 'Special database flag to use'
        required: false
        type: string
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Deploy database changes
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          DIRECT_URL: ${{ secrets.PROD_DIRECT_URL }}
          NODE_ENV: production
          DB_FLAG: ${{ inputs.db_flag }}
        run: |
          if [ -n "$DB_FLAG" ]; then
            npx prisma db push --$DB_FLAG
          else
            npx prisma db push 
          fi 