name: Verify Production Migrations

on:
  pull_request:
    paths:
      - 'prisma/migrations/**'
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - name: Install dependencies
        run: npm ci

      - name: Verify migrations
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
          DIRECT_URL: ${{ secrets.SUPABASE_DIRECT_URL }}
        run: |
          # Ensure we have both URLs
          if [ -z "$DATABASE_URL" ] || [ -z "$DIRECT_URL" ]; then
            echo "❌ DATABASE_URL or DIRECT_URL is not set"
            exit 1
          fi
          
          echo "Checking migration status..."
          if npx prisma migrate status | grep -q "Following migration have failed:"; then
            # Extract failed migration name and mark it as applied
            FAILED_MIGRATION=$(npx prisma migrate status | grep -A1 "Following migration have failed:" | tail -n1)
            echo "Found failed migration: $FAILED_MIGRATION"
            echo "Marking failed migration as applied since changes are already in database..."
            npx prisma migrate resolve --applied "$FAILED_MIGRATION"
          fi
          
          echo "Verifying migrations against production database..."
          npx prisma migrate deploy
          echo "✅ Production migrations verified successfully." 