name: Verify Production Migrations

on:
  pull_request:
    paths:
      - 'prisma/migrations/**'
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - name: Install dependencies
        run: npm ci

      - name: Verify migrations
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
          NODE_ENV: production
        run: |
          echo "Verifying migrations against production database..."
          npx prisma migrate deploy
          echo "✅ Production migrations verified successfully." 