name: SonarQube Analysis

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: read

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for full history

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Verify Secrets
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "❌ SONAR_TOKEN is missing!"
            exit 1
          fi
          if [ -z "${{ secrets.SONAR_HOST_URL }}" ]; then
            echo "❌ SONAR_HOST_URL is missing!"
            exit 1
          fi

      - name: Install Dependencies
        run: npm ci

      - name: Run Vitest & Generate Coverage
        run: npm run test

      - name: Check Coverage Output
        run: ls -la coverage/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
