name: Check Prisma Migration on PR to Develop

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Check if schema was changed without a migration
        run: |
          set -e
          
          # For testing with act, we'll check if we're in a test environment
          if [ -z "${{ github.base_ref }}" ]; then
            # Check if schema exists
            if [ -f "prisma/schema.prisma" ]; then
              SCHEMA_DIFF="exists"
            else
              SCHEMA_DIFF=""
            fi
            
            # Check for migrations
            if [ -d "prisma/migrations" ] && [ "$(ls -A prisma/migrations 2>/dev/null)" ]; then
              MIGRATIONS_EXIST="true"
            else
              MIGRATIONS_EXIST=""
            fi
          else
            # Fetch the base branch
            git fetch origin ${{ github.base_ref }}
            
            # Check if schema.prisma exists in base branch
            if git cat-file -e origin/${{ github.base_ref }}:prisma/schema.prisma 2>/dev/null; then
              SCHEMA_DIFF=$(git diff origin/${{ github.base_ref }}...HEAD -- prisma/schema.prisma || true)
            else
              SCHEMA_DIFF="new_file"
            fi
            
            # Check for migration files in this PR
            MIGRATIONS_EXIST=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep 'prisma/migrations/' || true)
          fi
          
          if [ ! -z "$SCHEMA_DIFF" ] && [ -z "$MIGRATIONS_EXIST" ]; then
            echo "❌ Schema changes detected but no migration was created!"
            echo "Changes found in schema.prisma but no corresponding migration file exists."
            echo "👉 Please run: npx prisma migrate dev --name your-feature-name"
            exit 1
          else
            echo "✅ Schema and migration check passed."
          fi