name: Check Prisma migration on PR to develop

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Check schema and migrations
        run: |
          set -e
          
          # Fetch the base branch
          git fetch origin ${{ github.base_ref }}
          
          # Check if schema.prisma exists in base branch
          if git cat-file -e origin/${{ github.base_ref }}:prisma/schema.prisma 2>/dev/null; then
            SCHEMA_DIFF=$(git diff origin/${{ github.base_ref }}...HEAD -- prisma/schema.prisma || true)
          else
            SCHEMA_DIFF="new_file"
          fi
          
          # Check for migration files in this PR
          MIGRATIONS_EXIST=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep 'prisma/migrations/' || true)
          
          if [ ! -z "$SCHEMA_DIFF" ] && [ -z "$MIGRATIONS_EXIST" ]; then
            echo "❌ Schema changes detected but no migration was created!"
            echo "Changes found in schema.prisma but no corresponding migration file exists."
            echo "👉 Please run: npx prisma migrate dev --name your-feature-name"
            exit 1
          fi
          
          # Check migration status
          echo "Checking migration status..."
          if ! npx prisma migrate status; then
            echo "❌ Migration check failed!"
            echo "This usually means your schema doesn't match your migrations."
            echo "👉 Run: npx prisma migrate dev to fix the mismatch"
            exit 1
          fi
          
          echo "✅ Schema and migration check passed."